unbind r
bind r source-file ~/.tmux.conf

set -g prefix C-s
set -g mouse on
set -g base-index 1

set -g status-right '#(f=$(basename "#{pane_current_path}" | awk "{if(length>25) print substr(\$0,1,22)\"...\"; else print}"); printf "󰉋 %%s" "$f"; cd "#{pane_current_path}" && b=$(git branch --show-current 2>/dev/null) && [ -n "$b" ] && { b=$(printf "%%s" "$b" | awk "{if(length>20) print substr(\$0,1,17)\"...\"; else print}"); printf "   %%s" "$b"; } || true) '
set -g status-interval 5

# vim like pane select
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# split panes
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# set-option -g status-position top
set -g default-terminal "tmux-256color"


# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# init with tmux plugin manager
run '~/.tmux/plugins/tpm/tpm'
